Repository daldang/daldang, pull requests merged in 2023-05, with the labels that each got.

#1 ci: Add prisma configuration for planetscale
  prisma/schema.prisma
Labels: enhancement

#7 Feat 5 routes and main
  package-lock.json
  package.json
  src/components/Calendar/Cells.tsx
  src/components/Calendar/Days.tsx
  src/components/Calendar/Header.tsx
  src/components/Calendar/index.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/record/index.tsx
Labels: enhancement

#11 feat: apply main design - calendar components
  src/components/Calendar/Cells.tsx
  src/components/Calendar/Days.tsx
  src/components/Calendar/Header.tsx
  src/components/Calendar/WeeklyCalendar.tsx
  src/components/Calendar/index.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: enhancement

#12 feat: Add `/record/add` page
  public/characters/croissant.svg
  public/characters/eggBread.svg
  public/characters/macaroon.svg
  public/characters/muffin.svg
  src/pages/record/add.tsx
  src/pages/record/index.tsx
  src/utils/hook.ts
  tailwind.config.ts
Labels: enhancement

#14 feat: Apply ui and styling for main page and done without api connection
  public/icons/dessert_shifta.png
  public/icons/icon_down.svg
  public/icons/icon_weekly_check.svg
  public/logo/logo_main.svg
  public/logo/logo_mypage.svg
  public/markers/marker.svg
  src/components/Calendar/Cells.tsx
  src/components/Calendar/Days.tsx
  src/components/Calendar/Header.tsx
  src/components/Calendar/WeeklyCalendar.tsx
  src/components/Calendar/index.tsx
  src/components/MainRecord/index.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
Labels: enhancement

#20 feat: mypage UI
  public/favicon.ico
  public/level/lv1.svg
  public/level/lv2.svg
  public/level/lv3.svg
  public/level/lv4.svg
  public/level/lv5.svg
  public/profile/profile_pic.png
  src/components/Calendar/Cells.tsx
  src/components/Calendar/WeeklyCalendar.tsx
  src/components/Calendar/index.tsx
  src/components/MainRecord/index.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  tailwind.config.ts
Labels: enhancement

#21 feat: Implements image upload feature
  package-lock.json
  package.json
  src/env.mjs
  src/pages/api/s3-upload.ts
  src/pages/record/add.tsx
  src/server/api/root.ts
  src/server/api/routers/desertLogs.ts
  src/utils/hook.ts
Labels: enhancement

#24 feat Implments `/signin` page
  public/images/back.png
  public/images/signin/background.png
  public/images/signin/google/1x/btn_google_signin_dark_disabled_web.png
  public/images/signin/google/1x/btn_google_signin_dark_focus_web.png
  public/images/signin/google/1x/btn_google_signin_dark_normal_web.png
  public/images/signin/google/1x/btn_google_signin_dark_pressed_web.png
  public/images/signin/google/1x/btn_google_signin_light_disabled_web.png
  public/images/signin/google/1x/btn_google_signin_light_focus_web.png
  public/images/signin/google/1x/btn_google_signin_light_normal_web.png
  public/images/signin/google/1x/btn_google_signin_light_pressed_web.png
  public/images/signin/google/2x/btn_google_signin_dark_disabled_web@2x.png
  public/images/signin/google/2x/btn_google_signin_dark_focus_web@2x.png
  public/images/signin/google/2x/btn_google_signin_dark_normal_web@2x.png
  public/images/signin/google/2x/btn_google_signin_dark_pressed_web@2x.png
  public/images/signin/google/2x/btn_google_signin_light_disabled_web@2x.png
  public/images/signin/google/light-focus-2x.png
  public/images/signin/google/light-normal-2x.png
  public/images/signin/google/light-pressed-2x.png
  public/images/signin/kakao/large-narrow.png
  public/images/signin/kakao/large-wide.png
  public/images/signin/kakao/medium-narrow.png
  public/images/signin/kakao/medium-wide.png
  public/images/signin/naver/btnG_축약형.png
  public/images/signin/naver/btnW_완성형.png
  public/images/signin/naver/btnW_축약형.png
  public/images/signin/naver/dark-short.png
  public/images/signin/naver/dark.png
  public/images/signin/naver/green.png
  public/logo/logo_signin.svg
  src/pages/signin.tsx
  src/server/auth.ts
Labels: enhancement

#26 feat: Add location by text input
  prisma/schema.prisma
  src/pages/record/add.tsx
  src/pages/records/[id].tsx
  src/server/api/routers/desertLogs.ts
  src/utils/hook.ts
Labels: enhancement

#27 fix: Add missing field `score` in create record
  src/pages/record/add.tsx
  src/server/api/routers/desertLogs.ts
  src/utils/hook.ts
Labels: bug

#28 fix: Updated getting and setting record data at main page (-ing)
  next.config.mjs
  src/components/Calendar/Cells.tsx
  src/components/Calendar/WeeklyCalendar.tsx
  src/components/Calendar/index.tsx
  src/components/MainRecord/index.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/utils/type.ts
Labels: enhancement

#30 refactor: Applied update my info-both name and image- feature
  src/pages/mypage/index.tsx
Labels: enhancement

#33 feat: Add redirection helper function with session
  src/pages/mypage/index.tsx
  src/pages/record/add.tsx
  src/pages/record/index.tsx
  src/pages/records/[id].tsx
  src/server/auth.ts
Labels: enhancement

#34 bug: setting default dessert name without typing dessert name
  src/components/Calendar/index.tsx
  src/pages/index.tsx
  src/pages/record/index.tsx
Labels: bug

#35 refactor: Simplify mypage state
  src/pages/mypage/index.tsx
Labels: enhancement

#36 feat: Implements signout feature
  src/pages/mypage/index.tsx
  src/server/api/root.ts
  src/server/api/routers/example.ts
  src/server/api/routers/user.ts
Labels: enhancement

#38 feat: Implements statistic for mypage
  src/pages/mypage/index.tsx
  src/pages/record/index.tsx
  src/server/api/routers/desertLogs.ts
  src/utils/type.ts
Labels: enhancement

#39 fix: Add access control to main page and styling sign in page
  public/images/signin.png
  src/components/MainRecord/index.tsx
  src/pages/index.tsx
  src/pages/record/index.tsx
  src/pages/signin.tsx
Labels: enhancement

#41 feat: Enable button on `/record/[id]`
  src/pages/record/add.tsx
  src/pages/records/[id].tsx
Labels: bug

#40 feat: Fix date error on MainRecord
  public/icons/icon_location.svg
  public/icons/icon_location_sm.svg
  public/images/record_bg_1.png
  public/images/record_bg_2.png
  src/components/Calendar/Cells.tsx
  src/components/Calendar/WeeklyCalendar.tsx
  src/components/Calendar/index.tsx
  src/components/MainRecord/index.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/record/add.tsx
  src/pages/records/[id].tsx
Labels: bug

#42 feat: Sort logs befer render in mypage
  src/pages/mypage/index.tsx
Labels: bug

#44 bug: bug fix
  src/components/Calendar/WeeklyCalendar.tsx
  src/components/Calendar/index.tsx
  src/components/MainRecord/index.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/record/add.tsx
  src/pages/records/[id].tsx
Labels: bug

#48 fix: Error on reducing empty array
  src/pages/mypage/index.tsx
Labels: bug

#50 feat: Add `/records/[id]/update` page
  src/pages/records/[id].tsx
  src/pages/records/[id]/update.tsx
  src/server/api/routers/desertLogs.ts
Labels: bug, enhancement

#51 bug: Fixed many things
  public/characters/cookie.svg
  src/components/Calendar/Cells.tsx
  src/components/Calendar/WeeklyCalendar.tsx
  src/components/Calendar/index.tsx
  src/pages/index.tsx
  src/pages/record/index.tsx
  src/utils/type.ts
Labels: bug
